language: java
jdk:
  - oraclejdk7
script: "mvn --show-version --errors --batch-mode clean org.jacoco:jacoco-maven-plugin:prepare-agent package
cache:
    directories:
    - $HOME/.m2
branches:
    except:
        - gh-pages